package br.inf.furb.tcc.robotoy.compiler.analyzer;

public interface ParserConstants
{
    String[] PARSER_ERROR =
    {
        "",
        "Era esperado fim de programa",
        "Era esperado \"+\"",
        "Era esperado \"-\"",
        "Era esperado \"*\"",
        "Era esperado \"/\"",
        "Era esperado \"%\"",
        "Era esperado \"(\"",
        "Era esperado \")\"",
        "Era esperado \">\"",
        "Era esperado \"<\"",
        "Era esperado \">=\"",
        "Era esperado \"<=\"",
        "Era esperado \"=\"",
        "Era esperado \"=/\"",
        "Era esperado \"<-\"",
        "Era esperado \".\"",
        "Era esperado quebra_de_linha",
        "Era esperado identificador",
        "Era esperado numerico",
        "Era esperado literal",
        "Era esperado numero",
        "Era esperado texto",
        "Era esperado nao",
        "Era esperado e",
        "Era esperado ou",
        "Era esperado andar",
        "Era esperado frente",
        "Era esperado tras",
        "Era esperado obstaculo",
        "Era esperado emitir",
        "Era esperado som",
        "Era esperado escrever",
        "Era esperado parar",
        "Era esperado roda",
        "Era esperado motor",
        "Era esperado multiuso",
        "Era esperado girar",
        "Era esperado virar",
        "Era esperado esquerda",
        "Era esperado direita",
        "Era esperado identificada",
        "Era esperado cor",
        "Era esperado branca",
        "Era esperado branco",
        "Era esperado preta",
        "Era esperado preto",
        "Era esperado vermelha",
        "Era esperado vermelho",
        "Era esperado amarela",
        "Era esperado amarelo",
        "Era esperado verde",
        "Era esperado azul",
        "Era esperado se",
        "Era esperado senao",
        "Era esperado enquanto",
        "Era esperado rotina",
        "Era esperado fim",
        "Era esperado tem",
        "Era esperado para",
        "Era esperado de",
        "Era esperado do",
        "Era esperado da",
        "Era esperado a",
        "<programa> inválido",
        "<lista_de_comandos> inválido",
        "<comando> inválido",
        "<controle_de_fluxo> inválido",
        "<se> inválido",
        "<senao> inválido",
        "<enquanto> inválido",
        "<definicao_de_variavel_ou_invocacao_de_metodo> inválido",
        "<declaracao_obrigatoria> inválido",
        "<declaracao_nao_obrigatoria> inválido",
        "<tipo> inválido",
        "<expressao> inválido",
        "<aritmetica> inválido",
        "<soma_subtracao> inválido",
        "<operacao> inválido",
        "<multiplicacao_divisao_resto> inválido",
        "<termo> inválido",
        "<concatenar_literal> inválido",
        "<opcoes_de_concatenacao> inválido",
        "<acao> inválido",
        "<andar> inválido",
        "<virar> inválido",
        "<girar_roda> inválido",
        "<parar> inválido",
        "<escrever> inválido",
        "<emitir_som> inválido",
        "<frente_ou_tras> inválido",
        "<esquerda_ou_direita> inválido",
        "<quantidade_de_vezes> inválido",
        "<quantidade_de_vezes_obrigatoria> inválido",
        "<acoes_que_param> inválido",
        "<condicao> inválido",
        "<tipo_condicao> inválido",
        "<condicao_extra> inválido",
        "<verificar_obstaculo> inválido",
        "<nao> inválido",
        "<comparar_numerico_literal> inválido",
        "<operador_relacional_numerico> inválido",
        "<cor> inválido",
        "<lista_de_rotinas> inválido",
        "<rotina> inválido"
    };
}
